default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5


production:
    adapter: postgresql
    encoding: unicode
    pool: 5


development:
    adapter: postgresql
    encoding: unicode
    database: ltatest
    pool: 5
    port: 5433
    username: maxore
